server:
  port: 80
  
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://ms-eureka-server:8761/eureka
      
spring:
  application:
    name: ms-gateway
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
      routes:
      - id: ms-person
        uri: lb://ms-person
        predicates:
        - Method=POST,GET,PUT,DELETE
        - Path= /ms-person/**